### ISSUE TITLE
Port over Upgrading

### ISSUE THREAD

**Issue by cah-danmonroe** [ember-learn/cli-guides-source#11]
I'll do this one as well.

**Comment by cah-danmonroe** [comment]
I'm going to remove this portion:  ```This is different from the existing ember init command. That command tries to reset your project back to a brand new project. It removes all your changes and additions.```

In my experience, running `ember init` is too destructive and tedious.

I'm also going to include the example from ember-cli-update

**Comment by jenweber** [comment]
I totally agree, now that we have such nice alternatives.

**Comment by jenweber** [comment]
closed by merging #13
